version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-trustpilot
            source /usr/local/share/virtualenvs/tap-trustpilot>/bin/activate
            pip install -U pip setuptools
            pip install .[dev]
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_trustpilot/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-trustpilot/bin/activate
            pylint tap_trustpilot --disable C,W,R

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only:
                - master